# Generated by Django 5.0.7 on 2024-08-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('github_link', models.URLField()),
                ('description', models.TextField()),
                ('technologies', models.CharField(max_length=200)),
            ],
        ),
    ]
