# Generated by Django 5.0.7 on 2024-08-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('technologies', models.CharField(max_length=255)),
                ('verification_link', models.URLField(blank=True, null=True)),
                ('offered_by', models.CharField(max_length=255)),
            ],
        ),
    ]
