# Generated by Django 5.0.7 on 2024-08-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_achievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_class', models.CharField(max_length=100)),
                ('college_name', models.CharField(max_length=255)),
                ('marks_obtained', models.FloatField()),
            ],
        ),
    ]
